### ISSUE TITLE
Text boxes wildly resizing and expanding whenever cursur enters the field, making the others stretch or shrink

### ISSUE THREAD

**Issue by LetsMakeaTulpa** [SingularityLabs-ai/MultiGPT-mini#15]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ishandutta2007** [comment]
@LetsMakeaTulpa **Hover on zoom** feature has been newly introduced on people's request to easily view the particular chatbox of their choice . If you wish to disable it just click on revert. 


![revert](https://github.com/SingularityLabs-ai/MultiGPT-mini/assets/2527354/aca8e718-79e7-46ee-8b23-981237ee3782)

**Comment by LetsMakeaTulpa** [comment]
thank you, happy ny

**Comment by ishandutta2007** [comment]
@LetsMakeaTulpa 
For any discussions or enhancement ideas on multiGPT feel free to initiate a thread [here](https://github.com/SingularityLabs-ai/MultiGPT-mini/discussions)
And for any other general AI ideas [here](https://github.com/SingularityLabs-ai)

**Comment by ishandutta2007** [comment]
If you have already accepeted/reverted it then to change it you have to go under theme settings

![under_theme_setting](https://github.com/SingularityLabs-ai/MultiGPT-mini/assets/2527354/b8c5c99c-3047-4814-8eeb-b470e6d4dd73)

https://www.loom.com/share/c3aa2ecb628848abbb0a8151ebebe149?sid=4f5e42c5-9fa3-45c9-a4df-ccd33b04f178
