### ISSUE TITLE
new released, add Claude 3, please

### ISSUE THREAD

**Issue by ozbillwang** [SingularityLabs-ai/MultiGPT-mini#25]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ishandutta2007** [comment]
Yes it's in our TODO list, but going forward most further enhancements will probably be only available for our premium users.

**Comment by ozbillwang** [comment]
Well done. :-)
