### ISSUE TITLE
Chatgpt error

### ISSUE THREAD

**Issue by hamzaraheel73** [SingularityLabs-ai/MultiGPT-mini#27]
Facing this error while trying to use Chatpt 3.5.
({"detail":"There was a problem with your chat request. Please use a different browser or try again later."})

**Comment by ishandutta2007** [comment]
@hamzaraheel73 is it working now for you in v0.0.41 ?

**Comment by hamzaraheel73** [comment]
@ishandutta2007 where did you release this version ? because on Chrome/edge it's still showing Version 0.0.29

**Comment by hamzaraheel73** [comment]
where you released version 0.0.41 because on edge, chrome , github its
still shows the old version 0.0.29

**Comment by ishandutta2007** [comment]
> 0.0.29

I mean 0.0.30, you have to wait for chrome team to complete the review process which might take 1-7 days.

**Comment by ishandutta2007** [comment]
> 0.0.29

By the way where in github is it showing 0.0.29 ?

**Comment by hamzaraheel73** [comment]
opps , no my fault, github is showing version 0.016  from Nov 2023.
Anyway Thanks team singularity for fixing this GPT error in multiGPT

**Comment by ishandutta2007** [comment]
@hamzaraheel73 which country/os/browser are you on ?

**Comment by hamzaraheel73** [comment]
Pakistan (Asia) / Window 11 / chrome and edge

**Comment by ishandutta2007** [comment]
@hamzaraheel73 MultiGPT's free preview ends very soon. For how many users are you looking to buy the license ?

**Comment by hamzaraheel73** [comment]
in which release you guys planning to integrate In App Purchase?
BTW am a single user...
But my bad on my first experience with MultiGPT I faced ChatGPT's that error.

**Comment by ishandutta2007** [comment]
@hamzaraheel73 free version uses free API's which chatGPT changes without informing us as a result it may show error from time to time. But Paid version will use paid API which they dont change without informing.

**Comment by ishandutta2007** [comment]
> BTW am a single user...

What's your monthly software purchases currently ?
We are talking with single users too to understand their requirements but we are only talking with people who are spending at least $200-$300 per month on various softwares which is very few in Asia, incase we don't come across many people in Asia the paid version will not be launched for Asia at all. And incase you are in that range despite being in Asia we are happy to discuss.
