### ISSUE TITLE
ChatGPT stopped working 

### ISSUE THREAD

**Issue by Ironcock** [SingularityLabs-ai/MultiGPT-mini#9]
ChatGPT seems to stop working for couple of days now. It keeps giving Message Timed out and asking to login. ChatGPT window is opened and logged in. 
Wepapp mode 3.5 
Browser Chrome and Vivaldi.

**Comment by Jenzam99** [comment]
Same issue I am having

**Comment by gaeco76** [comment]
i'm trying gpt3.5, 4.0  the question
but the answer is the question

**Comment by ishandutta2007** [comment]
@gaeco76 @Jenzam99  @Ironcock 
Can you guys clarify if this is the issue for all of you. on first query it is giving back the question itself and on continuing conversion it is timing out ?

If that's the issue then we have already submitted the fix to webstore. Please Wait for a couple of days for it to be approved by chrome webstore.

**Comment by ishandutta2007** [comment]
@gaeco76 @Jenzam99  @Ironcock it's live now, please update to version 0.0.15,
 let me know if the issue still exists.

**Comment by Ironcock** [comment]
Works good now, thank you!
